server:
  port: 7051
spring:
  datasource:
    url: jdbc:mysql://192.168.0.122:3306/yard_wms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # classpath* 将依赖包的 xml 也扫描到
  global-config:
    db-config:
      id-type: auto
